defmodule Laveno.Board.Maps do
  def offset_to_square(0), do: "h8"
  def offset_to_square(1), do: "g8"
  def offset_to_square(2), do: "f8"
  def offset_to_square(3), do: "e8"
  def offset_to_square(4), do: "d8"
  def offset_to_square(5), do: "c8"
  def offset_to_square(6), do: "b8"
  def offset_to_square(7), do: "a8"

  def offset_to_square(8), do: "h7"
  def offset_to_square(9), do: "g7"
  def offset_to_square(10), do: "f7"
  def offset_to_square(11), do: "e7"
  def offset_to_square(12), do: "d7"
  def offset_to_square(13), do: "c7"
  def offset_to_square(14), do: "b7"
  def offset_to_square(15), do: "a7"

  def offset_to_square(16), do: "h6"
  def offset_to_square(17), do: "g6"
  def offset_to_square(18), do: "f6"
  def offset_to_square(19), do: "e6"
  def offset_to_square(20), do: "d6"
  def offset_to_square(21), do: "c6"
  def offset_to_square(22), do: "b6"
  def offset_to_square(23), do: "a6"

  def offset_to_square(24), do: "h5"
  def offset_to_square(25), do: "g5"
  def offset_to_square(26), do: "f5"
  def offset_to_square(27), do: "e5"
  def offset_to_square(28), do: "d5"
  def offset_to_square(29), do: "c5"
  def offset_to_square(30), do: "b5"
  def offset_to_square(31), do: "a5"

  def offset_to_square(32), do: "h4"
  def offset_to_square(33), do: "g4"
  def offset_to_square(34), do: "f4"
  def offset_to_square(35), do: "e4"
  def offset_to_square(36), do: "d4"
  def offset_to_square(37), do: "c4"
  def offset_to_square(38), do: "b4"
  def offset_to_square(39), do: "a4"

  def offset_to_square(40), do: "h3"
  def offset_to_square(41), do: "g3"
  def offset_to_square(42), do: "f3"
  def offset_to_square(43), do: "e3"
  def offset_to_square(44), do: "d3"
  def offset_to_square(45), do: "c3"
  def offset_to_square(46), do: "b3"
  def offset_to_square(47), do: "a3"

  def offset_to_square(48), do: "h2"
  def offset_to_square(49), do: "g2"
  def offset_to_square(50), do: "f2"
  def offset_to_square(51), do: "e2"
  def offset_to_square(52), do: "d2"
  def offset_to_square(53), do: "c2"
  def offset_to_square(54), do: "b2"
  def offset_to_square(55), do: "a2"

  def offset_to_square(56), do: "h1"
  def offset_to_square(57), do: "g1"
  def offset_to_square(58), do: "f1"
  def offset_to_square(59), do: "e1"
  def offset_to_square(60), do: "d1"
  def offset_to_square(61), do: "c1"
  def offset_to_square(62), do: "b1"
  def offset_to_square(63), do: "a1"
end
